FROM node:16-alpine

WORKDIR /app

COPY --chown=node:node package.json /app/package.json
COPY --chown=node:node package-lock.json /app/package-lock.json

RUN npm install -g npm \
&& npm i -g @nestjs/cli \
&& npm ci
