export enum CustomStatusCode {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  PARAMETER_ERROR = 'PARAMETER_ERROR',
  DUPLICATE_USER_EMAIL = 'DUPLICATE_USER_EMAIL',
  DUPLICATE_USER_PHONE_NUMBER = 'DUPLICATE_USER_PHONE_NUMBER',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  VERIFICATION_NOT_FOUND = 'VERIFICATION_NOT_FOUND',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  CODE_MISMATCH = 'CODE_MISMATCH',
}
